malloydata/malloy-composer

src/app/AddFilter/AddFilter.tsx, src/app/AddNewDimension/AddNewDimension.tsx, src/app/AddNewMeasure/AddNewMeasure.tsx, src/app/CodeInput/CodeInput.tsx, src/app/CodeInput/index.ts, src/app/FieldList/FieldList.tsx, src/app/SelectDropdown/SelectDropdown.tsx, src/app/TypeIcon/TypeIcon.tsx, src/app/utils.ts, src/core/fields.ts
First pass at updated New Measure dialog. For https://github.com/looker-open-source/malloy/issues/604
=> New New Measure dialog

src/app/AddNewMeasure/AddNewMeasure.tsx, src/core/fields.ts
=> average -> avg

src/app/DownloadMenu/DownloadMenu.tsx, src/app/Result/Result.tsx, src/app/SelectDropdown/SelectDropdown.tsx, src/app/utils.ts
Fixes https://github.com/malloydata/malloy-composer/issues/20
=> New tab download

src/app/AddNewMeasure/AddNewMeasure.tsx, src/app/SelectDropdown/SelectDropdown.tsx, src/core/fields.ts
Change flow to start with field, make SelectDropdown focusable since it is now the first element, refine generated Malloy.
=> Updated New Measure UI

src/app/AddFilter/AddFilter.tsx, src/app/AddLimit/AddLimit.tsx, src/app/AddNewDimension/AddNewDimension.tsx, src/app/AddNewMeasure/AddNewMeasure.tsx, src/app/AddNewNest/AddNewNest.tsx, src/app/CommonElements.tsx, src/app/EditFilter/EditFilter.tsx, src/app/EditOrderBy/EditOrderBy.tsx, src/app/RenameField/RenameField.tsx, src/app/ReorderFieldsContextBar/ReorderFieldsContextBar.tsx, src/app/SaveQueryPopover/SaveQueryPopover.tsx
Use "Cancel" and "Save" consistently, make Cancel button background white.
=> Button cleanup

src/app/ActionIcon/ActionIcon.tsx, src/app/Explore/Explore.tsx, src/app/ExploreQueryEditor/ExploreQueryEditor.tsx, src/app/Result/Result.tsx, src/app/hooks/use_query_builder.ts, src/app/utils.ts, src/core/compile.ts, src/core/query.ts
=> Add ability to show Malloy code for source, model, or markdown

duckdb-wasm/composer.json, duckdb-wasm/flights_composer.json, src/app/Apps/Apps.tsx, src/app/Explore/Explore.tsx, src/app/data/duckdb_wasm.ts, src/app/data/use_datasets.ts, src/server/apps.ts, src/server/cli.ts, src/server/config.ts, src/server/datasets.ts, src/types/index.ts
Also changes the CLI to have the path as an argument rather than an option.
`composer .` or `composer ./samples/composer.json` rather than `composer --root composer.json`
=> Change name to path from root

src/app/AddNewDimension/AddNewDimension.tsx, src/app/AddNewMeasure/AddNewMeasure.tsx, src/app/GroupByContextBar/GroupByContextBar.tsx, src/app/NestQueryActionMenu/NestQueryActionMenu.tsx, src/app/SelectTimeGranularity/SelectTimeGranularity.tsx, src/app/SelectTimeGranularity/index.ts, src/app/StageActionMenu/StageActionMenu.tsx, src/app/TopQueryActionMenu/TopQueryActionMenu.tsx, src/app/utils.ts, src/core/compile.ts, src/core/fields.ts
Fixes https://github.com/looker-open-source/malloy/issues/603
TODO:
=> Allow selecting date granularity in group_by

src/app/Explore/Explore.tsx
Fixes https://github.com/looker-open-source/malloy/issues/890
=> Add link to docs

src/app/AddNewMeasure/AddNewMeasure.tsx, src/app/SelectDropdown/index.ts, src/core/fields.ts
Adds a selector for From a field, Count or Custom to the top of the measure to allow for one-stop measure creating and editing.
=> Two-step new measure

src/app/Explore/Explore.tsx
Fixes https://github.com/malloydata/malloy-composer/issues/50
=> Add loading spinner when loading app

scripts/package-server.ts
Add package versioning tag, and add all-targets flag to package script to create packages for all supported platforms
=> Add package versioning and all-targets flag.

bundle-readme.txt
Also signing failed for the mac binary so can fix that as well...
=> Fix attribute name in bundle readme

package-lock.json, package.json, src/app/GroupByContextBar/GroupByContextBar.tsx, src/app/utils.ts, src/core/fields.ts, src/core/query.ts
update how scalars, aggregates and analytic calculations encoded
=> update how scalars, aggregates and analytic calculations encoded

duckdb-wasm/flights.md, duckdb-wasm/flights_composer.json, scripts/build-duckdb-wasm.ts, src/app/data/duckdb_wasm.ts
Don't require "tables" map, allow configuring the default application URL when building.
=> Make config more flexible

scripts/build.ts, scripts/license_disclaimer.ts, scripts/utils/licenses.ts
Copy over from malloy-vscode-extension.
=> License file

src/server/server.ts
Allow spawning multiple composers, and add a shutdown endpoint.
=> Allow multiple composers

packages/query-composer/example/example.tsx, packages/query-composer/src/AggregateActionMenu/AggregateActionMenu.tsx, packages/query-composer/src/DataStyleActionMenu/DataStyleActionMenu.tsx, packages/query-composer/src/DataStyleContextBar/DataStyleContextBar.tsx, packages/query-composer/src/DimensionActionMenu/DimensionActionMenu.tsx, packages/query-composer/src/ExploreQueryEditor/ExploreQueryEditor.tsx, packages/query-composer/src/NestQueryActionMenu/NestQueryActionMenu.tsx, packages/query-composer/src/QuerySummaryPanel/QuerySummaryPanel.tsx, packages/query-composer/src/Result/Result.tsx, packages/query-composer/src/StageActionMenu/StageActionMenu.tsx, packages/query-composer/src/TopQueryActionMenu/TopQueryActionMenu.tsx, packages/query-composer/src/core/query.ts, packages/query-composer/src/hooks/use_query_builder.ts, src/app/Explore/Explore.tsx
Stub out renderer callback for now.
=> Update to latest renderer, remove DataStyles references

packages/query-composer/src/components/AggregateActionMenu/AggregateActionMenu.tsx, packages/query-composer/src/components/ExploreQueryEditor/ExploreQueryEditor.tsx, packages/query-composer/src/components/QuerySummaryPanel/QuerySummaryPanel.tsx, packages/query-composer/src/components/StageActionMenu/StageActionMenu.tsx, packages/query-composer/src/components/TopQueryActionMenu/TopQueryActionMenu.tsx, packages/query-composer/src/core/query.ts, packages/query-composer/src/hooks/use_query_builder.ts, packages/query-composer/src/types.ts
Update rendering menus to set tags on fields. Currently forcefully sets the current annotation structure.
=> Renderer work

package-lock.json, packages/query-composer/example/example.tsx, packages/query-composer/package.json, packages/query-composer/src/components/ExploreQueryEditor/ExploreQueryEditor.tsx, packages/query-composer/src/components/Result/Result.tsx, packages/query-composer/src/core/query.ts, packages/query-composer/src/data/use_run_query.ts, packages/query-composer/src/hooks/use_query_builder.ts, packages/query-composer/src/index.ts, packages/query-composer/tsconfig.json, scripts/license_disclaimer.ts, scripts/utils/licenses.ts, src/app/Apps/Apps.tsx, src/app/Explore/Explore.tsx, src/app/MarkdownDocument/MarkdownDocument.tsx, src/app/data/duckdb_wasm.ts, src/core/markdown.ts, src/server/datasets.ts, src/server/errors.ts, tsconfig.json
Separate query running from query building, compute a bunch of parameters, clean up React hook use. Turn on Typescript strict for part of project.
=> Query API Cleanup

packages/query-composer/src/core/dummy-compile.ts, packages/query-composer/src/core/fields.ts, packages/query-composer/src/core/filters.ts, packages/query-composer/src/core/query.ts, packages/query-composer/tests/core/dummy-compile.spec.ts, packages/query-composer/tests/core/fields.spec.ts, packages/query-composer/tests/core/filters.spec.ts
Fix some issues, remove redundant code.
=> Moar tests

package-lock.json, packages/query-composer/jest.config.ts, packages/query-composer/package.json, packages/query-composer/src/components/CodeInput/CodeInput.tsx, packages/query-composer/src/components/PillInput/PillInput.tsx, packages/query-composer/src/core/query.ts, packages/query-composer/tests/core/query.spec.ts
Add some tests, fix addFilterToField() issues uncovered by tests.
=> Add tests, fix addFilterToField

.eslintrc.json, package-lock.json, packages/query-composer/example/example_model.ts, packages/query-composer/package.json, packages/query-composer/src/components/ExploreQueryEditor/ExploreQueryEditor.tsx, packages/query-composer/src/contexts/search_context.ts, packages/query-composer/src/core/dummy-compile.ts, packages/query-composer/src/core/models.ts, packages/query-composer/src/data/index.ts, packages/query-composer/src/data/use_search.ts, packages/query-composer/src/hooks/use_query_builder.ts, packages/query-composer/tests/core/query.spec.ts, scripts/license_disclaimer.ts
Enable searching if an index has been provided.
=> Search on index

packages/query-composer/src/components/ActionMenu/ActionMenu.tsx, packages/query-composer/src/components/AggregateActionMenu/AggregateActionMenu.tsx, packages/query-composer/src/components/AggregateContextBar/AggregateContextBar.tsx, packages/query-composer/src/components/ExploreQueryEditor/ExploreQueryEditor.tsx, packages/query-composer/src/components/FieldDetailPanel/FieldDetailPanel.tsx, packages/query-composer/src/components/FieldList/FieldList.tsx, packages/query-composer/src/components/FilterContextBar/FilterContextBar.tsx, packages/query-composer/src/components/GroupByContextBar/GroupByContextBar.tsx, packages/query-composer/src/components/LoadTopQueryContextBar/LoadTopQueryContextBar.tsx, packages/query-composer/src/components/NestContextBar/NestContextBar.tsx, packages/query-composer/src/components/NestQueryActionMenu/NestQueryActionMenu.tsx, packages/query-composer/src/components/QuerySummaryPanel/QuerySummaryPanel.tsx, packages/query-composer/src/components/SearchList/SearchList.tsx, packages/query-composer/src/components/StageActionMenu/StageActionMenu.tsx, packages/query-composer/src/components/TopQueryActionMenu/TopQueryActionMenu.tsx
Switch to version from SearchContext
=> Stop prop-drilling topValues

packages/query-composer/src/core/query.ts
For now, may need to back to breaking things out by notes and blockNotes.
=> Use built in tagline utility

packages/query-composer/src/components/AddNewDimension/AddNewDimension.tsx, packages/query-composer/src/components/AddNewMeasure/AddNewMeasure.tsx
Fixes https://github.com/malloydata/malloy-composer/issues/216
=> Quote names when adding fields

packages/query-composer/src/core/filters.ts, packages/query-composer/tests/core/filters.spec.ts
Fixes https://github.com/malloydata/malloy-composer/issues/208
=> Generate correct in between filters

packages/query-composer/src/core/query.ts, packages/query-composer/tests/core/query.spec.ts
Fixes https://github.com/malloydata/malloy-composer/issues/214
=> More thorough empty check

packages/query-composer/src/components/QuerySummaryPanel/QuerySummaryPanel.tsx, packages/query-composer/src/components/QuerySummaryPanel/SummaryItem.tsx, packages/query-composer/src/components/SelectContextBar/SelectContextBar.tsx, packages/query-composer/src/components/SelectContextBar/index.ts, packages/query-composer/src/components/StageActionMenu/StageActionMenu.tsx, packages/query-composer/src/core/dummy-compile.ts
See https://github.com/malloydata/malloy-composer/issues/207
Still cannot create a project stage, but editing them is non-destructive now.
=> Minimal project stage support

packages/query-composer/src/core/query.ts
Fixes https://github.com/malloydata/malloy-composer/issues/235
=> Fix loadQuery() with a project stage

package-lock.json, package.json, packages/query-composer/package.json, packages/query-composer/src/components/TypeIcon/TypeIcon.tsx
Fall back to # icon. Update to latest Malloy.
=> Fix typeicon for sql native

packages/query-composer/src/components/DateInput/DateInput.tsx
Validate against YYYY-MM-DD instead of MM-DD-YYYY
=> Validate date strings more correctly

packages/query-composer/jest.config.ts, packages/query-composer/src/components/ErrorMessage/ErrorMessage.tsx, packages/query-composer/src/components/ErrorMessage/index.ts, packages/query-composer/src/components/QuerySummaryPanel/ClickToPopover.tsx, packages/query-composer/src/components/QuerySummaryPanel/FieldListDiv.tsx, packages/query-composer/src/components/QuerySummaryPanel/StageButton.tsx, packages/query-composer/src/components/QuerySummaryPanel/StateSummaryUI.tsx, packages/query-composer/src/components/QuerySummaryPanel/SummaryItem.tsx, packages/query-composer/src/components/SelectContextBar/index.ts, packages/query-composer/src/contexts/search_context.ts, packages/query-composer/src/core/dummy-compile.ts, packages/query-composer/src/core/models.ts, packages/query-composer/src/data/index.ts, packages/query-composer/src/data/use_search.ts, packages/query-composer/src/highlight.ts, packages/query-composer/tests/core/dummy-compile.spec.ts, packages/query-composer/tests/core/fields.spec.ts, packages/query-composer/tests/core/filters.spec.ts, packages/query-composer/tests/core/query.spec.ts, packages/query-composer/tests/core/utils.spec.ts, src/app/data/run_query.ts
Remove copy-pasta extra space.
=> Remove extra spaces

package-lock.json, packages/query-composer/jest.config.ts, packages/query-composer/package.json, packages/query-composer/src/core/models.ts, packages/query-composer/src/hooks/use_query_builder.ts, packages/query-composer/tests/core/query.spec.ts, packages/query-composer/tests/hooks/use_query_builder.spec.ts, packages/query-composer/tests/jest.setup.ts
First React hook tests, keeping chipping away at QueryBuilder
=> Add some more test

packages/query-composer/src/assets/img/query_clear_hover.svg, packages/query-composer/src/components/ActionIcon/ActionIcon.tsx, packages/query-composer/src/components/DatePicker/DatePicker.tsx, packages/query-composer/src/components/ExploreQueryEditor/ExploreQueryEditor.tsx, packages/query-composer/src/components/FieldButton/FieldButton.tsx, packages/query-composer/src/components/FieldDetailPanel/FieldDetailPanel.tsx, packages/query-composer/src/components/PillInput/PillInput.tsx, packages/query-composer/src/core/query.ts
Try and clean up keyboard behavior, add explicit "remove" to pill.
=> Pill behavior tweaks

packages/query-composer/src/components/AddFilter/StringFilterBuilder.tsx, packages/query-composer/src/components/FilterContextBar/FilterContextBar.tsx, packages/query-composer/src/components/PillInput/PillInput.tsx, packages/query-composer/src/core/filters.ts, packages/query-composer/tests/core/filters.spec.ts
Addresses most of https://github.com/malloydata/malloy-composer/issues/218, except for orange border. Removes some logging cruft.
=> Various filter fixes

packages/query-composer/src/components/NestContextBar/NestContextBar.tsx
Fixes https://github.com/malloydata/malloy-composer/issues/213
=> Don't show nests from joins

packages/query-composer/src/core/query.ts, packages/query-composer/src/hooks/use_query_builder.ts, packages/query-composer/tests/hooks/use_query_builder.spec.ts
=> Preserve filters when drilling

packages/query-composer/src/components/FieldList/FieldList.tsx, packages/query-composer/src/components/LoadTopQueryContextBar/LoadTopQueryContextBar.tsx
And remove redundant fragment.
=> Better key generation for queries

packages/query-composer/src/components/ActionIcon/ActionIcon.tsx, packages/query-composer/src/components/ParametersEditor/ParametersEditor.tsx, packages/query-composer/src/core/query_writer.ts
Instead of relying on `onBlur()`, which creates race conditions when the blur event is clicking the "Run" button
=> Explicit parameter edit

packages/query-composer/src/components/Result/Result.tsx, packages/query-composer/src/core/stub-compile.ts, packages/query-composer/tests/core/stub-compile.spec.ts
Always generate dynamic SQL and try to obtain the correct dialect from the source.
=> Dynamic SQL
