malloydata/malloy-composer

- src/app/Explore/Explore.tsx
- src/app/SelectDropdown/SelectDropdown.tsx
React doesn't like using fragments as list elements, because you can't assign them keys. This was giving us the `react_devtools_backend.js:4026 Warning: Each child in a list should have a unique "key" prop.` error in a few places. In one place the fragment turned out to be not necessary, but I got a little creative with the dividers.
> Fix key warnings

- src/app/Explore/Explore.tsx
Sloppy merge in https://github.com/malloydata/malloy-composer/commit/d581d6ea7f7b5bdd570da9f33aab4c3007bf48b6# caused 
```
runQuery();
setParams(urlParams);
```
To be erroneously removed (part of the code for running a query link). These are important... oops!
> Fix a sloppy merge at d581d6ea

- src/app/AddFilter/AddFilter.tsx
- src/app/AddLimit/AddLimit.tsx
- src/app/AddNewMeasure/AddNewMeasure.tsx
- src/app/AddNewNest/AddNewNest.tsx
- src/app/EditFilter/EditFilter.tsx
- src/app/EditOrderBy/EditOrderBy.tsx
- src/app/RenameField/RenameField.tsx
- src/app/ReorderFieldsContextBar/ReorderFieldsContextBar.tsx
- src/app/SelectDropdown/SelectDropdown.tsx
`<button>` elements default to `type="submit"` so form submissions were sometimes randomly firing and reloading the page.
> Prevent accidental form submissions

- src/app/ActionMenu/ActionMenu.tsx
- src/app/ExploreQueryEditor/ExploreQueryEditor.tsx
- src/app/NestQueryActionMenu/NestQueryActionMenu.tsx
- src/app/StageActionMenu/StageActionMenu.tsx
- src/app/TopQueryActionMenu/TopQueryActionMenu.tsx
- src/core/query.ts
- Move "Filter" and "Nest" to top of insert menu
- Move load query button nest to insert button
- Remove "Load Query" from insert menu
- Make load query button (the top level one next to the insert menu) keep filters if the query has no fields
> Big molecules

- src/app/Explore/Explore.tsx
- src/app/QuerySummaryPanel/QuerySummaryPanel.tsx
- src/app/hooks/use_query_builder.ts
- src/core/query.ts
- src/types/index.ts
Make the regular (expanded) nested query menu work for unexpanded nested queries, by auto-expanding. 
There seems to be a different bug https://github.com/malloydata/malloy-composer/issues/61 that causes the "Add stage" button to not work on nested queries regardless of whether auto-expanding is necessary.
> Auto expand nests

- scripts/create-release-bundles.ts
- src/app/Explore/Explore.tsx
Update the way bundles are named to allow usage of the 'latest' version when creating links to github versions.
Example:
https://github.com/malloydata/malloy-composer/releases/latest/download/malloy-composer-cli-macos-x64.zip
> Update bundle path/naming.

- src/app/Explore/Explore.tsx
- src/app/NestQueryActionMenu/NestQueryActionMenu.tsx
- src/app/QuerySummaryPanel/QuerySummaryPanel.tsx
https://github.com/malloydata/malloy-composer/pull/60 accidentally removed the ability to expand a query without modifying it. This PR adds it back.
> Add back "Duplicate" for nested saved queries

- src/app/Explore/Explore.tsx
- src/app/data/duckdb_wasm.ts
- src/types/index.ts
For duckdb-wasm only for now, instead of just a table name, you can now enter a table, url structure like:
```json
"tables": [
{
"name": "flights.parquet",
"url": "https://malloy.github.io/malloy-samples/duckdb/faa/data/flights.parquet"
},
{
"name": "carriers.parquet",
"url": "https://malloy.github.io/malloy-samples/duckdb/faa/data/carriers.parquet"
},
{
"name": "airports.parquet",
"url": "https://malloy.github.io/malloy-samples/duckdb/faa/data/airports.parquet"
}
]
```
and reference by name in Malloy
```malloy
source: flights is table('flights.parquet') {}
```
> Allow remote URLS for tables

- .eslintrc.cjs
- .gitignore
- package.json
- src/app/utils.ts
- src/core/compile.ts
esbuild doesn't report a lot of typescript build errors, so compile as part of linting.
> Catch more errors when linting

- .gitignore
- .gitmodules
- scripts/build.ts
- scripts/package-server.ts
- scripts/utils/fetch_duckdb.ts
- scripts/utils/fetch_node.ts
- third_party/github.com/evanw/esbuild/native-modules-plugin.ts
- third_party/github.com/evanw/esbuild/no-node-modules-sourcemaps.ts
Per a security bot's request, we will no longer rely on checked in binaries to package, instead fetching them on demand.
> Don't rely on checked in binaries

- package.json
Don't unlink, explicitly apply `@current` and `@next` to ensure only Malloy packages are affected.
> Updated update scripts

- .eslintrc.json
- packages/query-composer/src/core/dummy-compile.ts
- packages/query-composer/tests/core/query.spec.ts
- packages/query-composer/tests/core/utils.spec.ts
And fix `compileFilter()` to support both scalar (where:) and aggregate (having:) filter types.
> Add DummyCompiler tests

- packages/query-composer/src/core/query.ts
- packages/query-composer/tests/core/query.spec.ts
Add back visual `order_by` indicators, disallow multiple `order_by`s of the same name.
> Fix order_by bugs

- packages/query-composer/src/hooks/use_query_builder.ts
New value was being generated every time hook was invoked and not when specifically when query was changed.
> Debounce querySummary

- packages/query-composer/example/example.tsx
- packages/query-composer/src/hooks/index.ts
- packages/query-composer/src/hooks/use_query_builder.ts
Add simulated model refresh to example, fix query being discarded when model is refreshed.
> Preserve query when updating model

- packages/query-composer/src/components/ActionMenu/ActionMenu.tsx
- packages/query-composer/src/components/CommonElements.tsx
- packages/query-composer/src/components/FieldButton/FieldButton.tsx
- packages/query-composer/src/components/FieldList/FieldList.tsx
- packages/query-composer/src/components/LoadTopQueryContextBar/LoadTopQueryContextBar.tsx
- packages/query-composer/src/components/QueryEditor/QueryEditor.tsx
- packages/query-composer/src/components/SearchList/SearchList.tsx
- packages/query-composer/src/components/component_types.ts
- src/app/ChannelButton/ChannelButton.tsx
Now shift-click on a turtle merges with, not replaces, the existing query.
> Add support for mouse click modifiers

- packages/query-composer/src/components/ActionIcon/ActionIcon.tsx
- packages/query-composer/src/components/ExploreQueryEditor/ExploreQueryEditor.tsx
- packages/query-composer/src/components/QueryEditor/QueryEditor.tsx
- packages/query-composer/src/index.ts
- src/app/Explore/Explore.tsx
- src/app/data/use_top_values.ts
Top values can change as the model changes, so allow refreshing top values by shift-clicking refresh.
> Allow refreshing top values

- packages/query-composer/src/hooks/use_query_builder.ts
- packages/query-composer/tests/hooks/use_query_builder.spec.ts
querySummary needs to:
1. be kept in sync with queryBuilder.getQuerySummary()
2. be memoized for downstream use
> sync querySummary and queryBuilder

- packages/query-composer/src/hooks/use_query_builder.ts
Only passing Malloy to the history callback has some side-effects because they need to be re-compiled to be set on the query builder.
> Support non-serialized history

- package-lock.json
- package.json
- packages/query-composer/package.json
- packages/query-composer/src/components/Popover/Popover.tsx
react-popper is no longer supported, and has a peer dependency on React 18
> Replace popper with hover-ui
